server:
  port: 8079
  servlet:
    context-path: /api/v1
spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=miniProject;encrypt=false
    username:
    password:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect
app:
  host: http://localhost:8079/api/v1
logging:
  level:
    liquibase: DEBUG

